### ISSUE TITLE
Conversion from &T to &mut T is undefined behavior

### ISSUE THREAD

**Issue by dtolnay** [Aaronepower/region_buffer#4]
[This line](https://github.com/Aaronepower/region_buffer/blob/1063e9a4d0e4b19bb4460c7127435006fe5960c3/src/lib.rs#L258) together with [this line](https://github.com/Aaronepower/region_buffer/blob/1063e9a4d0e4b19bb4460c7127435006fe5960c3/src/lib.rs#L227) are taking `&self.region[index]` which is of type `&T`, then converting it to `*const T`, then to `*mut T`, then to `&mut T`. According to the Rustonomicon any such conversion is undefined behavior.

https://doc.rust-lang.org/nomicon/transmutes.html

> - Transmuting an & to &mut is UB
>   - Transmuting an & to &mut is *always* UB
>   - No you can't do it
>   - No you're not special

(The text refers to transmute but pointer cast + dereference has the same properties.)

In order for such a conversion to happen soundly there would need to be an [`UnsafeCell`](https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html) involved somewhere. That is the one and only way to safely go from &T to &mut T in Rust.

**Comment by XAMPPRocky** [comment]
Thanks for your issue! Haha yes I read that when I was first writing this and thought that since it didn't mention pointer casts it had different behaviour.
